# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('djangotest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('name', models.CharField(default='', max_length=20, primary_key=True, serialize=False, verbose_name='用户名')),
                ('sex', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='性别')),
                ('age', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='年龄')),
                ('university', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='所在高校')),
                ('major', models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='所读专业')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('address', models.CharField(max_length=100, verbose_name='联系地址')),
                ('message', models.CharField(max_length=500, verbose_name='留言信息')),
            ],
            options={
                'verbose_name': '用户留言信息',
                'verbose_name_plural': '用户留言信息',
            },
        ),
    ]
